### ISSUE TITLE
Add support to libcurl-impersonate

### ISSUE THREAD

**Issue by GunGunGun** [karpierz/libcurl#3]
Because so many websites nowadays use Cloudflare to fingerprint and harass users with captcha and anti-bot checks, the normal curl is actually less useful than curl with TLS spoofing abilities.

For example this website will send a captcha or bot check page if you use normal curl to open it, but  it's not the case with curl-impersonate.

Linux and Mac binaries https://github.com/lwthiker/curl-impersonate

For Windows it's still a WIP, but usable:
Windows binaries https://github.com/depler/curl-impersonate-win
curl-impersonate-win Firefox https://github.com/qwerty12/subliminal/wiki/Building-curl-impersonate-Firefox-for-Windows-x64

**Comment by karpierz** [comment]
Sorry.. I have no plans to use impersonate libcurl :(.
This project only wraps/use the official libcurl library.
PS: Of course is possible to use any libcurl dll/so with this wrapper library.
Take a look at README.rst:

libcurl-ct uses the underlying libcurl C shared library as specified in libcurl.cfg (included libcurl-X.X.* is the default),
but there is also ability to specify it programmatically by one of the following ways:
```import libcurl
libcurl.config(LIBCURL="libcurl C shared library absolute path")
# or
libcurl.config(LIBCURL=None)  # included libcurl-X.X.* will be use
```
